### ISSUE TITLE
FullCalendar is not loading

### ISSUE THREAD

**Issue by misrapk** [bhrugen/AppointmentScheduler#2]
While loading the calendar in Appointment/index, it is showing error "TypeError: $(...).fullCalendar is not a function"

**Comment by brunotdantas** [comment]
Hey @misrapk  did you copy the content of the custom js from here? https://github.com/bhrugen/AppointmentScheduler/blob/master/AppointmentScheduling/wwwroot/js/script-custom-calendar.js

**Comment by brunotdantas** [comment]
On Class 84 (https://www.udemy.com/course/aspnet-core-5-mvc/learn/lecture/24520176#questions)  I had the same issue. Reading https://fullcalendar.io/docs/initialize-globals 

I managed to fix this issue like this: 

```javascript
document.addEventListener('DOMContentLoaded', function () {

    var calendar;
        try {


            var calendarEl = document.getElementById('calendar');
            if (calendarEl != null) {
                calendar = new FullCalendar.Calendar(calendarEl, {
                    initialView: 'dayGridMonth',
                    headerToolbar: {
                        left: 'prev,next,today',
                        center: 'title',
                        right: 'dayGridMonth,timeGridWeek,timeGridDay'
                    },
                    selectable: true,
                    editable: false
                });
                calendar.render();
            } else
                alert(calendarEl);

        }
        catch (e) {
            alert(e);
        }

    
});
```

this is the result 
![image](https://user-images.githubusercontent.com/19207320/133944051-84e44089-a85d-42e5-b815-d7f5e123dfec.png)

**Comment by misrapk** [comment]
Thanks, it works now
